{{- if .Values.opentelemetry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ .Values.opentelemetry.namespace }}
  labels:
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: collector
spec:
  replicas: {{ .Values.opentelemetry.collector.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetry
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:latest
        ports:
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        resources:
          {{- toYaml .Values.opentelemetry.collector.resources | nindent 10 }}
{{- end }}
