{{- if and .Values.cilium.gatewayAPI.enabled .Values.jaeger.ingress.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jaeger-route
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  parentRefs:
  - name: cloudflare-gateway
    namespace: gateway-system
  hostnames:
  - "{{ .Values.jaeger.ingress.hostname }}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: jaeger-query
      port: 16686
      namespace: observability
{{- end }}
