apiVersion: v2
name: serverless-infra
description: Serverless Infrastructure Subchart (Knative, Kourier, Jaeger, OpenTelemetry, etc.)
version: 1.0.0
appVersion: "1.0"

keywords:
  - kubernetes
  - serverless
  - knative
  - kourier
  - jaeger
  - opentelemetry
maintainers:
  - name: BenedictusAryo
home: https://github.com/BenedictusAryo/cluster-serverless
sources:
  - https://github.com/BenedictusARYO/cluster-serverless
