{{- $repoURL := .Values.repoURL -}}
{{- $targetRevision := .Values.targetRevision -}}
{{- $destServer := .Values.destinationServer -}}
{{- $sync := .Values.syncPolicy | default dict -}}
{{- $argocdNamespace := .Values.argocdNamespace -}}
{{/*
  Generate individual ArgoCD Applications for each app in appsList
*/}}
{{- range .Values.appsList }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-{{ .name }}
  namespace: {{ $argocdNamespace }}
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    path: {{ .path }}
    directory:
      recurse: true
  destination:
    server: {{ $destServer }}
    namespace: {{ .namespace }}
  {{- if $sync }}
  syncPolicy:
    {{- if $sync.automated }}
    automated:
      prune: {{ $sync.prune | default false }}
      selfHeal: {{ $sync.selfHeal | default false }}
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  {{- end }}
{{- end }}
{{/*
  Generate ArgoCD Application for infrastructure apps
*/}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.infraApp.name }}
  namespace: {{ $argocdNamespace }}
spec:
  project: {{ .Values.infraApp.project | default "default" }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}
    path: {{ .Values.infraApp.path }}
    directory:
      recurse: true
  destination:
    server: {{ $destServer }}
    namespace: {{ .Values.infraApp.namespace }}
  {{- if $sync }}
  syncPolicy:
    {{- if $sync.automated }}
    automated:
      prune: {{ $sync.prune | default false }}
      selfHeal: {{ $sync.selfHeal | default false }}
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  {{- end }}
