apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.argocdNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.appsNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.infraNamespace }}
