apiVersion: v2
name: serverless-app
description: Serverless Applications Subchart (Example hello-world app)
version: 1.0.0
appVersion: "1.0"

keywords:
  - kubernetes
  - serverless
  - knative
  - applications
maintainers:
  - name: BenedictusAryo
home: https://github.com/BenedictusAryo/cluster-serverless
sources:
  - https://github.com/BenedictusARYO/cluster-serverless