{{- if .Values.kourier.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: kourier-system
  labels:
    app.kubernetes.io/name: kourier-system
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}