repoURL: https://github.com/BenedictusAryo/cluster-serverless.git
targetRevision: HEAD
argocdNamespace: argocd
appsNamespace: apps
infraNamespace: infra
destinationServer: https://kubernetes.default.svc
syncPolicy:
  automated: true
  prune: true
  selfHeal: true
# Individual app configurations
appsList:
  - name: blog
    path: apps/blog
    namespace: apps
    project: default
  - name: pdf-utils
    path: apps/pdf-utils
    namespace: apps
    project: default
  - name: wa-notif
    path: apps/wa-notif
    namespace: apps
    project: default

# Infrastructure apps configuration
infraApp:
  name: infra-apps
  path: infra-apps
  namespace: infra
  project: default
