{{- if .Values.jaeger.ingress.enabled }}
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jaeger-proxy
  namespace: {{ .Values.jaeger.namespace }}
spec:
  template:
    metadata:
      annotations:
        # Scale to 1 always (not scale-to-zero)
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
      - image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: jaeger-nginx-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-nginx-proxy
  namespace: {{ .Values.jaeger.namespace }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://jaeger-query.{{ .Values.jaeger.namespace }}.svc.cluster.local:16686;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: jaeger.benedict-aryo.com
  namespace: {{ .Values.jaeger.namespace }}
spec:
  ref:
    name: jaeger-proxy
    kind: Service
    apiVersion: serving.knative.dev/v1
{{- end }}
