{{- if .Values.jaeger.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-query
  namespace: {{ .Values.jaeger.namespace }}
  labels:
    app.kubernetes.io/name: jaeger-query-ingress
    app.kubernetes.io/part-of: jaeger
spec:
  ingressClassName: kourier.ingress.networking.knative.dev
  rules:
  - host: {{ .Values.jaeger.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger-query
            port:
              number: 16686
{{- end }}
